export const usersList= [
  {
    id: 1,
    img: "/facebook/user/ГургенАбагян.jpeg",
    name: "Гурген Абагян",
    userOnline: true,
    stories: true,
    comment: "wdkn l,lef",
  },
  {
    id: 2,
    img: "/facebook/user/Рафаел Кочарян.jpeg",
    name: "Рафаел Кочарян",
    userOnline: true,
    stories: true,
    comment: "ha ba vonc",
  },
  {
    id: 3,
    img: "/facebook/profilicon.png",
    name: "Christine Avanesyan",
    userOnline: true,
    stories: false,
    comment: "hasel es ich",
  },
  {
    id: 4,
    img: "/facebook/profilicon.png",
    name: "Name Surname",
    userOnline: false,
    stories: false,
    comment: "barlis",
  },
  {
    id: 5,
    img: "/facebook/facebook.jpg",
    name: "Arshak Nalbandyan",
    userOnline: false,
    comment: "wdn owodwd",
    stories: false,
  },
  {
    id: 6,
    img: "/facebook/user/Сергей Денисов.jpeg",
    name: "Сергей Денисов",
    stories: false,
    userOnline: true,
    comment: "jgig jhftyft",
  },
  {
    id: 7,
    img: "/facebook/user/Shushan S-yan.jpeg",
    name: "Shushan S-yan",
    stories: false,
    userOnline: false,
    comment: "jkbjb jbb",
  },
  {
    id: 8,
    img: "/facebook/user/Spartak Qocharyan .jpeg",
    name: "Spartak Qocharyan",
    stories: false,
    userOnline: false,
    comment: "kjgkb gfsdsdfx ljoj",
  },
  {
    id: 9,
    img: "/facebook/user/Anna Muradyan.jpeg",
    name: "Anna Muradyan",
    stories: false,
    userOnline: false,
    comment: "jhhbxxd  kjhuv htc",
  },
  {
    id: 10,
    img: "/facebook/user/Kristi Araqelyan.jpeg",
    name: "Kristi Araqelyan",
    stories: true,
    userOnline: true,
    comment: "jhvjh gbkb",
  },
  {
    id: 11,
    img: "/facebook/user/Сергей Денисов.jpeg",
    name: "Сергей Денисов",
    stories: false,
    userOnline: true,
    comment: "jgig jhftyft",
  },
  {
    id: 12,
    img: "/facebook/facebook.jpg",
    name: "Arshak Nalbandyan",
    userOnline: false,
    comment: "wdn owodwd",
    stories: false,
  },
];


