export const usersList= [
  {
    id: 1,
    img: "/facebook/user/ГургенАбагян.jpeg",
    name: "Гурген Абагян",
    userOnline: true,
    stories: true,
    comment: "gg7i  nnnkk nnnnnn9u89u9",
  },
  {
    id: 2,
    img: "/facebook/user/Рафаел Кочарян.jpeg",
    name: "Рафаел Кочарян",
    userOnline: true,
    stories: true,
    comment: "gg7i  nnnkk nnnnnn9u89u9",
  },
  {
    id: 3,
    img: "/facebook/profilicon.png",
    name: "Christine Avanesyan",
    userOnline: true,
    stories: false,
    comment: "gg7i  nnnkk nnnnnn9u89u9",
  },
  {
    id: 4,
    img: "/facebook/profilicon.png",
    name: "Yura Arzumanyan",
    userOnline: false,
    stories: false,
    comment: "gg7i  nnnkk nnnnnn9u89u9",
  },
  {
    id: 5,
    img: "/facebook/facebook.jpg",
    name: "Toma Abagyan",
    userOnline: false,
    comment: "gg7i  nnnkk nnnnnn9u89u9",
    stories: false,
  },
  {
    id: 6,
    img: "/facebook/user/Сергей Денисов.jpeg",
    name: "Сергей Денисов",
    stories: false,
    userOnline: true,
    comment: "gg7i  nnnkk nnnnnn9u89u9",
  },
  {
    id: 7,
    img: "/facebook/user/Shushan S-yan.jpeg",
    name: "Shushan S-yan",
    stories: false,
    userOnline: false,
    comment: "gg7i  nnnkk nnnnnn9u89u9",
  },
  {
    id: 8,
    img: "/facebook/user/Spartak Qocharyan .jpeg",
    name: "Spartak Qocharyan",
    stories: false,
    userOnline: false,
    comment: "gg7i  nnnkk nnnnnn9u89u9",
  },
  {
    id: 9,
    img: "/facebook/user/Anna Muradyan.jpeg",
    name: "Anna Muradyan",
    stories: false,
    userOnline: false,
    comment: "gg7i  nnnkk nnnnnn9u89u9",
  },
  {
    id: 10,
    img: "/facebook/user/Kristi Araqelyan.jpeg",
    name: "Kristi Araqelyan",
    stories: true,
    userOnline: true,
    comment: "gg7i  nnnkk nnnnnn9u89u9",
  },
];


